name: lda
checkpoint: False
representation: heavy_atom_distance
model: {
  in_features: 45,
  n_states: 2,
  mode: "standard"
}
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.1,
    patience: 50
  }
  batch_size: 2000
  max_epochs: 2000
logger:
  name: wandb
  project: mlcv2
  log_model: False
  tags:
  - baseline