name: tae
checkpoint: False
representation: heavy_atom_coordinate
model: {
  encoder_layers: [30, 100, 100, 1],
  options: {
    encoder: {
      activation: "tanh",
      dropout: [0.5, 0.5, 0.5]
    },
    decoder: {
      activation: "tanh"
    },
    norm_in: {
    },
  },
  reference_frame: ../simulation/data/alanine/c5.pt,
}
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.1,
    patience: 50
  }
  batch_size: 2000
  max_epochs: 1000
logger:
  name: wandb
  project: mlcv2
  log_model: False
  tags:
  - baseline
