name: tbgcv-xyzhad
checkpoint: False
representation: heavy_atom_coordinate_distance
model: {
  encoder_layers: [75, 100, 100, 1],
  options: {
    encoder: {
      activation: "tanh",
      dropout: [0.5, 0.5, 0.5]
    },
    norm_in: {
    }
  },
}
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.01,
    patience: 100
  }
  batch_size: 2000
  max_epochs: 1000
logger:
  name: wandb
  project: mlcv2
  log_model: False
  tags:
  - method