name: tbgcv
checkpoint: True
checkpoint_name: mlcv
representation: heavy_atom_distance
model: {
  encoder_layers: [45, 30, 30, 1],
  options: {
    encoder: {
      activation: "relu"
    },
    norm_in: {
    }
  }
}
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.01,
    patience: 100
  }
  batch_size: 2000
  max_epochs: 1000
logger:
  name: wandb
  project: mlcv2
  log_model: False
  tags:
  - method