name: vde
checkpoint: False
representation: heavy_atom_distance
model: {
  n_cvs: 1,
  encoder_layers: [45, 100, 100, 1],
  options: {
    encoder: {
      activation: "swish",
      dropout: [0.5, 0.5, 0.5],
      last_layer_activation: True
    },
    decoder: {
      activation: "swish"
    },
    norm_in: {
    },
  },
}
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.1,
    patience: 50
  }
  batch_size: 2000
  max_epochs: 1000
logger:
  name: wandb
  project: mlcv2
  log_model: False
  tags:
  - baseline
