image: docker:latest

services:
- docker:dind

before_script:
- ip a s
- apk add --update bash make sed git curl
- docker version
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"



build-all:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/$CI_REGISTRY_USER/gromacs:latest .
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/gromacs:latest
  only:
    - master
